### ISSUE TITLE
Doesn't compile on Linux

### ISSUE THREAD

**Issue by bigfug** [rabbitControl/rcp-cpp#2]
Just tried compiling on Ubuntu 18.04 LTS (also Raspberry Pi with same result):

```
pi@raspberrypi:~/rcp-cpp/build` $ make
Scanning dependencies of target RCP
[ 11%] Building CXX object CMakeFiles/RCP.dir/src/color.cpp.o
[ 11%] Building CXX object CMakeFiles/RCP.dir/rcptest.cpp.o
[ 17%] Building CXX object CMakeFiles/RCP.dir/src/ip.cpp.o
[ 23%] Building CXX object CMakeFiles/RCP.dir/src/packet.cpp.o
[ 29%] Building CXX object CMakeFiles/RCP.dir/src/parameter_group.cpp.o
In file included from /home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:57,
                 from /home/pi/rcp-cpp/rcp-cpp/src/packet.h:38,
                 from /home/pi/rcp-cpp/rcp-cpp/src/rcp.h:42,
                 from /home/pi/rcp-cpp/rcp-cpp/rcptest.cpp:38:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In constructor ‘rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::Value::Value(rcp::IParameter&)’:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:241:17: error: there are no arguments to ‘memset’ that depend on a template parameter, so a declaration of ‘memset’ must be available [-fpermissive]
                 memset(uuid, 0, 16);
                 ^~~~~~
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:241:17: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In constructor ‘rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::Value::Value(const string&, rcp::IParameter&)’:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:253:17: error: there are no arguments to ‘memset’ that depend on a template parameter, so a declaration of ‘memset’ must be available [-fpermissive]
                 memset(uuid, 0, 16);
                 ^~~~~~
In file included from /home/pi/rcp-cpp/rcp-cpp/src/packet.h:38,
                 from /home/pi/rcp-cpp/rcp-cpp/src/rcp.h:42,
                 from /home/pi/rcp-cpp/rcp-cpp/rcptest.cpp:38:
/home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h: In member function ‘void rcp::Parameter<TD>::Value::write(rcp::Writer&, bool)’:
/home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:781:36: warning: invalid use of incomplete type ‘using element_type = class rcp::GroupParameter’ {aka ‘class rcp::GroupParameter’}
                         out.write(p->getId());
                                    ^~
In file included from /home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:47,
                 from /home/pi/rcp-cpp/rcp-cpp/src/packet.h:38,
                 from /home/pi/rcp-cpp/rcp-cpp/src/rcp.h:42,
                 from /home/pi/rcp-cpp/rcp-cpp/rcptest.cpp:38:
/home/pi/rcp-cpp/rcp-cpp/src/iparameter.h:48:11: note: forward declaration of ‘using element_type = class rcp::GroupParameter’ {aka ‘class rcp::GroupParameter’}
     class GroupParameter;
           ^~~~~~~~~~~~~~
In file included from /home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:57,
                 from /home/pi/rcp-cpp/rcp-cpp/src/packet.h:38,
                 from /home/pi/rcp-cpp/rcp-cpp/src/packet.cpp:35:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In constructor ‘rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::Value::Value(rcp::IParameter&)’:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:241:17: error: there are no arguments to ‘memset’ that depend on a template parameter, so a declaration of ‘memset’ must be available [-fpermissive]
                 memset(uuid, 0, 16);
                 ^~~~~~
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:241:17: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In constructor ‘rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::Value::Value(const string&, rcp::IParameter&)’:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:253:17: error: there are no arguments to ‘memset’ that depend on a template parameter, so a declaration of ‘memset’ must be available [-fpermissive]
                 memset(uuid, 0, 16);
                 ^~~~~~
In file included from /home/pi/rcp-cpp/rcp-cpp/src/packet.h:38,
                 from /home/pi/rcp-cpp/rcp-cpp/src/packet.cpp:35:
/home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h: In member function ‘void rcp::Parameter<TD>::Value::write(rcp::Writer&, bool)’:
/home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:781:36: warning: invalid use of incomplete type ‘using element_type = class rcp::GroupParameter’ {aka ‘class rcp::GroupParameter’}
                         out.write(p->getId());
                                    ^~
In file included from /home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:47,
                 from /home/pi/rcp-cpp/rcp-cpp/src/packet.h:38,
                 from /home/pi/rcp-cpp/rcp-cpp/src/packet.cpp:35:
/home/pi/rcp-cpp/rcp-cpp/src/iparameter.h:48:11: note: forward declaration of ‘using element_type = class rcp::GroupParameter’ {aka ‘class rcp::GroupParameter’}
     class GroupParameter;
           ^~~~~~~~~~~~~~
In file included from /home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:57,
                 from /home/pi/rcp-cpp/rcp-cpp/src/parameter_group.cpp:35:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In constructor ‘rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::Value::Value(rcp::IParameter&)’:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:241:17: error: there are no arguments to ‘memset’ that depend on a template parameter, so a declaration of ‘memset’ must be available [-fpermissive]
                 memset(uuid, 0, 16);
                 ^~~~~~
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:241:17: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In constructor ‘rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::Value::Value(const string&, rcp::IParameter&)’:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:253:17: error: there are no arguments to ‘memset’ that depend on a template parameter, so a declaration of ‘memset’ must be available [-fpermissive]
                 memset(uuid, 0, 16);
                 ^~~~~~
In file included from /home/pi/rcp-cpp/rcp-cpp/src/parameter_group.cpp:35:
/home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h: In member function ‘void rcp::Parameter<TD>::Value::write(rcp::Writer&, bool)’:
/home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:781:36: warning: invalid use of incomplete type ‘using element_type = class rcp::GroupParameter’ {aka ‘class rcp::GroupParameter’}
                         out.write(p->getId());
                                    ^~
In file included from /home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:47,
                 from /home/pi/rcp-cpp/rcp-cpp/src/parameter_group.cpp:35:
/home/pi/rcp-cpp/rcp-cpp/src/iparameter.h:48:11: note: forward declaration of ‘using element_type = class rcp::GroupParameter’ {aka ‘class rcp::GroupParameter’}
     class GroupParameter;
           ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/RCP.dir/build.make:102: CMakeFiles/RCP.dir/src/packet.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:57,
                 from /home/pi/rcp-cpp/rcp-cpp/src/packet.h:38,
                 from /home/pi/rcp-cpp/rcp-cpp/src/rcp.h:42,
                 from /home/pi/rcp-cpp/rcp-cpp/rcptest.cpp:38:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In instantiation of ‘void rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::setUuid(const char*, uint8_t) [with T = int; uint8_t = unsigned char]’:
/home/pi/rcp-cpp/rcp-cpp/src/parameter_custom.h:67:13:   required from ‘void rcp::CustomParameter<T>::setUuid(char*, uint8_t) [with T = int; uint8_t = unsigned char]’
/home/pi/rcp-cpp/rcp-cpp/rcptest.cpp:365:27:   required from here
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:174:23: error: ‘memcmp’ was not declared in this scope
             if (memcmp(obj->uuid, uuid, 16) == 0) {
                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:174:23: note: ‘memcmp’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:1:1:
+#include <cstring>
 /*
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:174:23:
             if (memcmp(obj->uuid, uuid, 16) == 0) {
                 ~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:178:19: error: ‘memcpy’ was not declared in this scope
             memcpy(obj->uuid, uuid, 16);
             ~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:178:19: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
make[2]: *** [CMakeFiles/RCP.dir/build.make:115: CMakeFiles/RCP.dir/src/parameter_group.cpp.o] Error 1
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In instantiation of ‘void rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::Value::write(rcp::Writer&, bool) [with T = int]’:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:74:13:   required from ‘void rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::write(rcp::Writer&, bool) [with T = int]’
/home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:979:13:   required from ‘void rcp::ValueParameter<T, TD, type_id>::write(rcp::Writer&, bool) [with T = int; TD = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>; datatype_t type_id = (datatype_t)1]’
/home/pi/rcp-cpp/rcp-cpp/rcptest.cpp:370:29:   required from here
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:277:27: error: ‘memset’ was not declared in this scope
                     memset(&v, 0, sizeof(T));
                     ~~~~~~^~~~~~~~~~~~~~~~~~
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:277:27: note: ‘memset’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In instantiation of ‘rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::Value::Value(rcp::IParameter&) [with T = int]’:
/usr/include/c++/8/ext/new_allocator.h:136:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value; _Args = {rcp::IParameter&}; _Tp = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value]’
/usr/include/c++/8/bits/alloc_traits.h:475:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value; _Args = {rcp::IParameter&}; _Tp = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value>]’
/usr/include/c++/8/bits/shared_ptr_base.h:545:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {rcp::IParameter&}; _Tp = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value; _Alloc = std::allocator<rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)1]’
/usr/include/c++/8/bits/shared_ptr_base.h:677:16:   required from ‘std::__shared_count<_Lp>::__shared_count(_Tp*&, std::_Sp_alloc_shared_tag<_Alloc>, _Args&& ...) [with _Tp = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value; _Alloc = std::allocator<rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value>; _Args = {rcp::IParameter&}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)1]’
/usr/include/c++/8/bits/shared_ptr_base.h:1342:71:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value>; _Args = {rcp::IParameter&}; _Tp = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)1]’
/usr/include/c++/8/bits/shared_ptr.h:359:59:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/c++/8/bits/shared_ptr.h:721:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>::Value; _Args = {rcp::IParameter&}]’
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:60:40:   required from ‘rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::TypeDefinition(rcp::IParameter&) [with T = int]’
/home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:97:45:   required from ‘rcp::Parameter<TD>::Parameter(int16_t) [with TD = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>; int16_t = short int]’
/home/pi/rcp-cpp/rcp-cpp/src/parameter_intern.h:949:42:   required from ‘rcp::ValueParameter<T, TD, type_id>::ValueParameter(int16_t) [with T = int; TD = rcp::TypeDefinition<int, (datatype_t)1, (td_types)6>; datatype_t type_id = (datatype_t)1; int16_t = short int]’
/home/pi/rcp-cpp/rcp-cpp/src/parameter_custom.h:55:32:   required from ‘rcp::CustomParameter<T>::CustomParameter(int16_t) [with T = int; int16_t = short int]’
/home/pi/rcp-cpp/rcp-cpp/rcptest.cpp:364:33:   required from here
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:241:23: error: ‘memset’ was not declared in this scope
                 memset(uuid, 0, 16);
                 ~~~~~~^~~~~~~~~~~~~
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:241:23: note: ‘memset’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h: In instantiation of ‘void rcp::TypeDefinition<T, (datatype_t)1, (td_types)6>::parseOptions(std::istream&) [with T = int; std::istream = std::basic_istream<char>]’:
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:82:14:   required from here
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:127:27: error: ‘memcpy’ was not declared in this scope
                     memcpy(&obj->config[0], &data[0], data_length);
                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/rcp-cpp/rcp-cpp/src/type_custom.h:127:27: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
make[2]: *** [CMakeFiles/RCP.dir/build.make:63: CMakeFiles/RCP.dir/rcptest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/RCP.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`
```

**Comment by i-n-g-o** [comment]
thanks for reporting.
i pushed  missing include, it should compile now.

**Comment by bigfug** [comment]
Last push fixes compilation for Raspberry Pi and Ubuntu 18.04+ but still fails on Ubuntu 16.04:

```
In file included from /home/alex/rcp-cpp/src/packet.h:38:0,
                 from /home/alex/rcp-cpp/src/rcp.h:42,
                 from /home/alex/rcp-cpp/rcptest.cpp:38:
/home/alex/rcp-cpp/src/parameter_intern.h: In member function ‘void rcp::Parameter<TD>::Value::write(rcp::Writer&, bool)’:
/home/alex/rcp-cpp/src/parameter_intern.h:781:36: error: invalid use of incomplete type ‘class rcp::GroupParameter’
                         out.write(p->getId());
                                    ^
In file included from /home/alex/rcp-cpp/src/parameter_intern.h:47:0,
                 from /home/alex/rcp-cpp/src/packet.h:38,
                 from /home/alex/rcp-cpp/src/rcp.h:42,
                 from /home/alex/rcp-cpp/rcptest.cpp:38:
/home/alex/rcp-cpp/src/iparameter.h:48:11: note: forward declaration of ‘class rcp::GroupParameter’
     class GroupParameter;
           ^
CMakeFiles/RCP.dir/build.make:62: recipe for target 'CMakeFiles/RCP.dir/rcptest.cpp.o' failed
```

**Comment by i-n-g-o** [comment]
yeah, i got a warning about this.

it should be fixed now. compiles for me on ubuntu 18.04 without warning.
please have a try.

**Comment by bigfug** [comment]
Confirmed this now compiles on Ubuntu 16.04 too - thank you :)
